### ISSUE TITLE
Общий кэшбек не может быть больше лимита, а не с каждой покупки

### ISSUE THREAD

**Issue by coursar** [dilshod-ship-it/homeworkCashback#2]
https://github.com/dilshod-ship-it/homeworkCashback/blob/9964b63a21e0ffb3a6853f61b91fdfe395c9765a/src/js/app.js#L34-L37

**Comment by coursar** [comment]
Вот это надо было вынести из `for`:

https://github.com/dilshod-ship-it/homeworkCashback/blob/e2843c0bd5819a3375f52e21d3678c33b09ed6ce/src/js/app.js#L40-L42

**Comment by coursar** [comment]
Читайте внимательно замечания

**Comment by dilshod-ship-it** [comment]
Извините, поторопился, поэтому не обратил внимание на ошибку
